# eQ-OS Main Configuration
[Output]
Format=disk
Output=eQ-OS
OutputDirectory=ISO
ImageVersion=0.0.2
SplitArtifacts=yes

[Distribution]
Distribution=debian
Release=trixie
RepositoryKeyFetch=true

[Build]
WithNetwork=yes
ToolsTree=default
PackageCacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
Incremental=yes
BuildSourcesEphemeral=buildcache
Environment=MKOSI_CHROOT_SUPPRESS_CHOWN=1

[Validation]
Checksum=yes
Verity=signed
VerityKey=mkosi.key
VerityCertificate=mkosi.crt