[Distribution]
Distribution=debian
Release=trixie
RepositoryKeyFetch=yes

[PackageSet]
PackageSet=minimal

[Output]
Format=disk
Output=eQ-OS
OutputDirectory=ISO
SplitArtifacts=yes

[Build]
WithNetwork=yes
ToolsTree=default
PackageCacheDirectory=mkosi.cache
Incremental=yes
Environment=MKOSI_CHROOT_SUPPRESS_CHOWN=1

[Validation]
Checksum=yes

[Kernel]
CommandLine=splash

[Content]
Bootable=yes
Bootloader=grub
Packages=
    # Core system
    linux-image-amd64
    systemd
    systemd-sysv
    dbus
    udev
    util-linux
    build-essential
    dpkg
    
    # Kiosk
    whiptail
    xterm
    polkitd

    # GRUB for BIOS + UEFI
    grub-efi-amd64
    grub-efi-amd64-bin
    efibootmgr

    # Basics
    ca-certificates
    passwd
    login
    usrmerge
    libpam-modules
    libpam-runtime

    # Rust
    libgcc-s1
    libc6
    git
    curl
    pkg-config

    # Minimal X11
    xserver-xorg
    xserver-xorg-core
    xserver-xorg-video-dummy
    xserver-xorg-input-libinput
    xserver-xorg-input-kbd
    libinput10
    xinit
    x11-utils
    x11-xserver-utils
    mesa-utils
    libgl1-mesa-dri
    libglx-mesa0

    # GUI libs
    libx11-6
    libx11-xcb1
    libxcb1
    libxcb-render0
    libxcb-shape0
    libxcb-xfixes0
    libxkbcommon0
    libxkbcommon-x11-0
    libfontconfig1
    libfreetype6

    # Fonts
    fonts-dejavu-core

    # Plymouth
    plymouth
    plymouth-themes

CleanPackageMetadata=yes
RemoveFiles=
    /usr/share/doc/*
    /usr/share/man/*
    /usr/share/info/*
    /usr/share/locale/*/!C*
    /var/cache/apt/*
    /var/lib/apt/lists/*