[Distribution]
Distribution=debian
Release=trixie
RepositoryKeyFetch=yes

[Output]
Format=disk
Output=eQ-OS
OutputDirectory=ISO

[Content]
Bootable=yes
Bootloader=uki
RootPassword=eQ

Packages=
    # Core
    linux-image-amd64
    util-linux
    systemd
    systemd-sysv
    systemd-boot-efi
    dbus
    udev
    passwd

    # Runtime deps for your Rust binary
    libgcc-s1
    libc6

    # DRM / input (for fbdev/DRM access)
    libdrm2
    libgbm1
    libinput10
    libudev1

    # Fonts
    fonts-dejavu-core
    libfontconfig1
    libfreetype6

[Build]
WithNetwork=yes

[Validation]
Checksum=yes

[Kernel]
UKI=yes