[Content]
Bootable=yes
Bootloader=grub
Locale=en_US.UTF-8
Timezone=Etc/UTC
Hostname=eQ-OS
CleanPackageMetadata=yes

KernelCommandLine=
    quiet splash
    plymouth.ignore-serial-consoles
    loglevel=3 audit=0
    systemd.show_status=false
    rd.luks=0 rd.eqstate.label=eQ rd.eqstate.mount=/eQ

RemoveFiles=
    /usr/share/doc/*
    /usr/share/man/*
    /usr/share/info/*
    /usr/share/locale/*/!C*
    /var/cache/apt/*
    /var/lib/apt/lists/*
    /usr/share/help/*
    /usr/share/zoneinfo/*
    /usr/lib/systemd/catalog/*