[Content]
BuildPackages=
    build-essential
    git
    curl
    pkg-config
    dpkg-dev

Packages=
    # Core system
    linux-image-amd64
    systemd
    systemd-sysv
    dbus
    udev
    util-linux
    dracut

    # GRUB
    grub-efi-amd64
    grub-efi-amd64-bin
    efibootmgr

    # Basics
    ca-certificates
    passwd
    login
    usrmerge
    libpam-modules
    libpam-runtime
    libpam-systemd

    # Rust & libs
    libgcc-s1
    libc6

    # Minimal X11 / Graphics
    xserver-xorg
    xserver-xorg-core
    xserver-xorg-video-dummy
    xserver-xorg-input-libinput
    libinput10
    xinit
    x11-utils
    x11-xserver-utils
    mesa-utils
    libgl1-mesa-dri
    libglx-mesa0
    libx11-6
    libx11-xcb1
    libxcb1
    libxcb-render0
    libxcb-shape0
    libxcb-xfixes0
    libfontconfig1
    libfreetype6
    fonts-dejavu-core

    # Plymouth
    plymouth
    plymouth-themes
    
    # Encryption
    cryptsetup