# Blacklist Wi-Fi modules
blacklist iwlwifi           # Intel Wi-Fi
blacklist ath9k             # Atheros 802.11n wireless
blacklist ath10k            # Atheros 802.11ac wireless
blacklist rt2800pci         # Ralink RT2800 PCI wireless
blacklist rt2800usb         # Ralink RT2800 USB wireless
blacklist brcmfmac          # Broadcom 802.11ac wireless

# Blacklist Ethernet modules
blacklist e1000e            # Intel PRO/1000 Gigabit Ethernet
blacklist e1000             # Intel PRO/1000 Gigabit Ethernet
blacklist r8169             # Realtek RTL8169 Gigabit Ethernet
blacklist tg3               # Broadcom Tigon3 Gigabit Ethernet
blacklist sky2              # Skyworks Solutions Inc. SKY2 Ethernet

# Blacklist Bluetooth and webcam modules
blacklist btusb             # Bluetooth USB
blacklist uvcvideo          # USB video class (webcam)

# Blacklist other communication modules
blacklist nfc               # Near Field Communication
blacklist rfkill            # Radio Frequency Kill
blacklist snd-hda-intel     # Sound

# Blacklist keyboard modules
blacklist serio_raw         # Serial I/O for raw devices
blacklist atkbd             # AT keyboard driver
blacklist psmouse           # PS/2 mouse driver
blacklist usbhid            # USB human interface device