Section "InputClass"
    Identifier "Disable Keyboard"
    MatchIsKeyboard "on"
    Option "Ignore" "true"
EndSection

Section "InputClass"
    Driver "libinput"
    Identifier "Enable Mouse and Pointers"
    MatchIsPointer "on"
    MatchIsTouchpad "on"
    Option "Ignore" "false"
EndSection

Section "InputClass"
    Identifier "Enable Other Input Devices"
    MatchIsJoystick "off"
    MatchIsTablet "off"
    Option "Ignore" "false"
    Driver "libinput"
EndSection