Section "ServerFlags"
    Option "UseLogind" "false"
    Option "DontVTSwitch" "true"
    Option "DontZap" "true"
    Option "AutoAddDevices" "true"
    Option "AutoEnableDevices" "true"
    Option "AllowMouseOpenFail" "true"

    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection